Repository tapestry-tool/tapestry-wp, pull requests merged in 2019-10, with the labels that each got.

#158 Linted Master
  templates/vue/.eslintrc.js
  templates/vue/.vscode/extensions.json
  templates/vue/.vscode/settings.json
  templates/vue/package.json
  templates/vue/src/App.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/main.js
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/utils/Helpers.js
Labels: refactoring

#162 Improve overall performance
  templates/tapestry.js
Labels: enhancement

#170 Fixed video duration showing when duration is zero
  templates/tapestry.js
Labels: bug

#168 Video should be skippable by default
  templates/tapestry.js
Labels: bug
