Repository tapestry-tool/tapestry-wp, pull requests merged in 2019-11, with the labels that each got.

#173 172 do not allow icons to move with drag
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/Tapestry.vue
Labels: enhancement

#180 Added background audio
  templates/vue/src/components/Tyde.vue
  templates/vue/src/components/tyde/TydeMenu.vue
  templates/vue/src/components/tyde/TydeMenuSettings.vue
Labels: TYDE

#175 174 Delete associated links when deleting a node
  classes/class.tapestry-node.php
  classes/class.tapestry.php
  templates/tapestry.js
Labels: bug

#202 Delete setting h5pSettings
  templates/vue/src/components/Lightbox.vue
Labels: bug
