Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-11, with the labels that each got.

#806 805 - add link error handling
  templates/vue/src/App.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryError.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/index.js
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/errorHelper.js
Labels: ready for review

#812 804 - Bug Fix: Delete child nodes when links swapped
  templates/vue/src/components/node-modal/DeleteNodeButton.vue
  templates/vue/src/store/getters.js
Labels: ready for review

#819 817 - Bug Fix: Errors in NodeModal causing infinite load
  templates/vue/src/components/NodeModal.vue
Labels: ready for review

#824 823 - Bug fix: Cannot use Ctrl/Cmd + A to select all nodes if logged in
  templates/vue/src/components/SettingsModal.vue
Labels: ready for review

#839 838 - Accordions display child nodes twice
  templates/vue/src/components/NodeModal.vue
Labels: ready to merge

#828 826 - Bug fix: Mispositioned media buttons in Safari
  templates/vue/src/components/TapestryIcon.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/tapestry-node/AddChildButton.vue
  templates/vue/src/components/tapestry-node/NodeButton.vue
Labels: ready to merge

#810 809 - fixes for dragselect in sidebar and filter button
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryNode.vue
Labels: ready for review

#843 842 - Bug Fix: Fix unable to delete links
  templates/vue/src/components/NodeModal.vue
Labels: ready to merge

#834 833 - Add WordPress layer to front-end
  templates/vue/.eslintrc.js
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/LockedTooltip.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/components/TapestryLink.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/lightbox/quiz-screen/AnswerButton.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  templates/vue/src/components/node-modal/content-form/H5pForm.vue
  templates/vue/src/components/node-modal/content-form/Icon.vue
  templates/vue/src/services/__mocks__/wp.js
  templates/vue/src/services/wp.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/wp.js
Labels: needs testing

#707 653 - Integrate Cypress to run automatically on Github
  .github/workflows/ci.yml
  .gitignore
  tapestry.php
  templates/vue/cypress.gha.json
  templates/vue/cypress/fixtures/accordion.json
  templates/vue/cypress/fixtures/one-node.json
  templates/vue/cypress/fixtures/three-nodes.json
  templates/vue/cypress/fixtures/two-nodes.json
  templates/vue/cypress/fixtures/user.json
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/cypress/integration/lightbox/embed.spec.js
  templates/vue/cypress/integration/lightbox/video.spec.js
  templates/vue/cypress/integration/link-authoring.spec.js
  templates/vue/cypress/integration/media-types/accordion.spec.js
  templates/vue/cypress/integration/media-types/embed.spec.js
  templates/vue/cypress/integration/navigation.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/node-locked.spec.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/cypress/integration/settings.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/utils.js
  templates/vue/package-lock.json
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/lightbox/EndScreen.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
  templates/vue/src/components/tapestry-node/NodeButton.vue
  templates/vue/src/main.js
  templates/vue/src/store/actions.js
  templates/vue/src/utils/Helpers.js
Labels: ready for review

#836 835 - Refactor and improve test utilities
  templates/vue/package.json
  templates/vue/src/components/__tests__/Lightbox.spec.js
  templates/vue/src/components/__tests__/TapestryApp.spec.js
  templates/vue/src/components/settings-modal/__tests__/DuplicateTapestryButton.spec.js
  templates/vue/src/router.js
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/dataset.js
  templates/vue/src/utils/test.js
Labels: ready for review

#856 855 - Bug fix: Youtube components not working in jest
  templates/vue/config/jest-setup.js
  templates/vue/jest.config.js
Labels: ready for review

#683 680 - accept/reject: Allow users to submit nodes and resubmit rejected nodes
  classes/class.tapestry-node.php
  classes/class.tapestry.php
  endpoints.php
  templates/vue/config/jest-setup.js
  templates/vue/cypress/integration/lightbox/embed.spec.js
  templates/vue/cypress/integration/review.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/roles.js
  templates/vue/src/App.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/node-modal/DeleteNodeButton.vue
  templates/vue/src/components/node-modal/ReviewForm.vue
  templates/vue/src/components/node-modal/__tests__/ReviewForm.spec.js
  templates/vue/src/components/tapestry-node/ProgressBar.vue
  templates/vue/src/components/tapestry-node/StatusBar.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/services/wp.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/test.js
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#822 821 - Bug Fix: No error handling when invalid URL for Video
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/__tests__/NodeModal.spec.js
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/services/__mocks__/wp.js
Labels: ready for review

#858 733 - Text on node with thumbnail is hard to read
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryNode.vue
Labels: ready to merge

#863 Add PR template
  .github/pull_request_template.md
Labels: ready for review

#830 829 - YouTube videos don't set the a thumbnail
  templates/vue/cypress/integration/lightbox/video.spec.js
  templates/vue/cypress/integration/node-appearance.spec.js
  templates/vue/debug.log
  templates/vue/src/components/NodeModal.vue
Labels: ready for review

#692 691 - Add tapestry setting to load a map of earth instead of tapestry
  classes/class.tapestry-node.php
  templates/vue/.gitignore
  templates/vue/__mocks__/styleMock.js
  templates/vue/config/webpack.base.js
  templates/vue/cypress/integration/tapestry-map.spec.js
  templates/vue/debug.log
  templates/vue/jest.config.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/App.vue
  templates/vue/src/assets/map-marker-draft.png
  templates/vue/src/assets/map-marker-inaccessible.png
  templates/vue/src/assets/map-marker.png
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/components/TapestryMap.vue
  templates/vue/src/components/node-modal/CoordinatesForm.vue
Labels: ready to merge

#871 870- Urgent fix: Unable to add root node
  templates/vue/src/utils/Helpers.js
Labels: ready to merge

#865 837 - Bug Fix: Hide disjoint accordion nodes
  templates/vue/cypress/fixtures/deep-accordion.json
  templates/vue/cypress/integration/lightbox/accordion.spec.js
  templates/vue/src/components/tapestry-node/AddChildButton.vue
  templates/vue/src/store/getters.js
Labels: ready to merge, waiting for answer

#867 866 - Bug fix: New text legibility feature has flickering animation
  templates/vue/src/components/TapestryNode.vue
Labels: needs work

#882 881 - test(e2e): update root node test
  templates/vue/cypress/integration/node-authoring.spec.js
Labels: ready for review

#869 857 - Bug fix: CI Docker container does not have permission on file upload directories (Cypress testing)
  .github/workflows/ci.yml
  templates/vue/cypress/integration/lightbox/embed.spec.js
  templates/vue/cypress/integration/settings.spec.js
Labels: ready to merge
