Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-07, with the labels that each got.

#616 615 - Fix WP content types changing when new posts get added
  templates/vue/src/services/WordpressApi.js
Labels: needs testing

#620 602 - Bug fix: Fix tapestry settings getting reset
  classes/class.tapestry.php
  tapestry.php
  utilities/class.tapestry-node-permissions.php
Labels: needs testing

#614 613 - Disable submit button when node is submitting
  templates/vue/src/components/NodeModal.vue
Labels: needs testing

#607 606 - Unable to Edit Activity Nodes with Questions
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/node-modal/ContentForm.vue
Labels: ready for review

#621 600 - Bug fix: New nodes are locked by default
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
Labels: needs testing

#619 617 - Bug fix: Tapestry doesn't load if some nodes for associated links have been deleted
  templates/tapestry.js
  templates/vue/src/components/Tapestry.vue
Labels: needs testing

#544 Ensure password protection works for tapestries (TYDE)
  tapestry.php
  templates/single-tapestry.php
Labels: ready for review

#554 553 - Allow author to set default tapestry depth
  templates/tapestry.js
  templates/vue/src/components/SettingsModal.vue
Labels: ready for review

#585 584 - Cannot link locked nodes
  templates/tapestry.js
Labels: ready for review

#587 586 - Refactor tyde and master branches to minimize conflicts
  .githooks/pre-commit
  classes/class.constants.php
  classes/class.tapestry-audio.php
  classes/class.tapestry-form.php
  classes/class.tapestry-group.php
  classes/class.tapestry-h5p.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  docker/wp-config-sample.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  interfaces/interface.tapestry-form.php
  interfaces/interface.tapestry-group.php
  interfaces/interface.tapestry-h5p.php
  interfaces/interface.tapestry-node.php
  interfaces/interface.tapestry-user-progress.php
  interfaces/interface.tapestry.php
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/EndScreen.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
  templates/vue/src/components/lightbox/quiz-screen/AnswerButton.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-node-permissions.php
  utilities/class.tapestry-permissions.php
  utilities/class.tapestry-user-roles.php
Labels: ready for review

#630 628 - Enable hiding nodes from Admin and implement Author filter in backend
  .gitignore
  classes/class.tapestry.php
  endpoints.php
  interfaces/interface.tapestry.php
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-user-roles.php
Labels: needs testing

#638 637 - Bug: Cannot Load Old Tapestries with Author Filter
  classes/class.tapestry.php
Labels: ready for review

#640 639 - Bug fix: Links don't show up when nodes are added
  tapestry.php
  templates/vue/src/components/NodeModal.vue
Labels: needs testing

#642 641 - Bug fix: Copilots are not able to complete accordion rows
  templates/vue/src/components/lightbox/AccordionMedia.vue
Labels: needs testing

#644 Fix hot reload
  templates/vue/webpack.config.js
Labels: ready for review

#636 634 - Bug fix: Unable to load submit button in node modal
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/node-modal/content-form/H5pForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
Labels: ready for review

#647 Delete YoutubeMedia.vue
  templates/vue/src/components/lightbox/YoutubeMedia.vue
Labels: needs testing

#626 625 - Bug fix: Unable to drop a thumbnail image
  templates/vue/src/components/FileUpload.vue
Labels: ready to merge

#591 TYDE: 586 - Refactor tyde and master branches to minimize conflicts
  .githooks/pre-commit
  classes/class.constants.php
  classes/class.tapestry-form.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  docker/Dockerfile
  docker/docker-compose.yml
  docker/upload.ini
  docker/wp-init.sh
  endpoints.php
  interfaces/interface.tapestry-user-progress.php
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/.vscode/extensions.json
  templates/vue/.vscode/settings.json
  templates/vue/Dockerfile
  templates/vue/cypress-sample.json
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/ModalButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryActivity.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/Tyde.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/EndScreen.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/QuizScreen.vue
  templates/vue/src/components/lightbox/TextMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
  templates/vue/src/components/lightbox/YouTubeMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
  templates/vue/src/components/lightbox/quiz-screen/AnswerButton.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/tyde/TydeActivitySummary.vue
  templates/vue/src/components/tyde/TydeLog.vue
  templates/vue/src/store/getters.js
  templates/vue/src/store/index.js
  templates/vue/src/store/mutations.js
  templates/vue/src/tyde.scss
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/constants.js
  templates/vue/webpack.config.js
Labels: ready for review

#611 29-06-2020 - Merge master into tyde
  classes/class.tapestry-node.php
  classes/class.tapestry.php
  templates/tapestry.js
  templates/vue/lint.js
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/store/getters.js
Labels: ready for review

#635 633 - Bug fix: Video thumbnail duration showing decimals
  templates/tapestry.js
Labels: ready for review

#597 583 - Switch all textareas to allow formatting options and links
  templates/e2e/cypress.json
  templates/e2e/cypress/screenshots/authoring.spec.js.zip
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to add and see a root node (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to add child nodes (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to delete a leaf node (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open add modal (failed) (1).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open add modal (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open edit modal (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should be able to open lightbox by clicking on center of node if media button is hidden (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide media button (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide node title (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide progress bar (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should show a thumbnail if a thumbnail url is passed (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a Gravity Form and have the form be visible (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a quiz to a video and have that quiz appear at the end of the video (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a text node and verify that the text matches what was entered (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a video url and length and have the video load (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add an external link node and have it show a summary of the external page (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Should be able to edit content fields and see the changes applied (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide add button if user does not have add access (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide edit button if user does not have write access (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide node and associated links if user does not have read access (failed).png
  templates/e2e/cypress/videos/authoring.spec.js.mp4
  templates/e2e/cypress/videos/user.spec.js.mp4
  templates/tapestry.css
  templates/vue/package.json
  templates/vue/src/assets/icons/add_col_after.svg
  templates/vue/src/assets/icons/add_col_before.svg
  templates/vue/src/assets/icons/add_row_after.svg
  templates/vue/src/assets/icons/add_row_before.svg
  templates/vue/src/assets/icons/bold.svg
  templates/vue/src/assets/icons/checklist.svg
  templates/vue/src/assets/icons/code.svg
  templates/vue/src/assets/icons/combine_cells.svg
  templates/vue/src/assets/icons/delete_col.svg
  templates/vue/src/assets/icons/delete_row.svg
  templates/vue/src/assets/icons/delete_table.svg
  templates/vue/src/assets/icons/github.svg
  templates/vue/src/assets/icons/hr.svg
  templates/vue/src/assets/icons/image.svg
  templates/vue/src/assets/icons/italic.svg
  templates/vue/src/assets/icons/link.svg
  templates/vue/src/assets/icons/mention.svg
  templates/vue/src/assets/icons/ol.svg
  templates/vue/src/assets/icons/paragraph.svg
  templates/vue/src/assets/icons/quote.svg
  templates/vue/src/assets/icons/redo.svg
  templates/vue/src/assets/icons/remove.svg
  templates/vue/src/assets/icons/strike.svg
  templates/vue/src/assets/icons/table.svg
  templates/vue/src/assets/icons/ul.svg
  templates/vue/src/assets/icons/underline.svg
  templates/vue/src/assets/icons/undo.svg
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/components/node-modal/content-form/ActivityForm.vue
  templates/vue/src/components/node-modal/content-form/Icon.vue
  templates/vue/src/components/node-modal/content-form/RichTextForm.vue
  templates/vue/src/components/node-modal/content-form/TextForm.vue
Labels: needs testing

#581 579 - Containerize Modular Cypress Tests
  .gitignore
  docker/docker-compose.yml
  templates/e2e/cypress-sample.json
  templates/e2e/cypress/fixtures/example.json
  templates/e2e/cypress/fixtures/root.json
  templates/e2e/cypress/fixtures/two-nodes.json
  templates/e2e/cypress/fixtures/user.json
  templates/e2e/cypress/integration/authoring.spec.js
  templates/e2e/cypress/integration/user.spec.js
  templates/e2e/cypress/plugins/index.js
  templates/e2e/cypress/support/commands.js
  templates/e2e/cypress/support/index.js
  templates/e2e/cypress/support/roles.js
  templates/e2e/cypress/support/utils.js
  templates/vue/package.json
Labels: ready to merge

#593 588 - Permissions showing unchecked for "Editor" role
  templates/vue/src/components/node-modal/PermissionsTable.vue
Labels: ready to merge

#596 595 - Tooltips at the Top of a Tapestry Get Hidden
  templates/tapestry.js
Labels: ready to merge

#599 594 - Allow creation of tapestry using a shortcode / button / widget
  classes/class.tapestry.php
  tapestry.php
Labels: needs testing

#631 629 - Newly added nodes should not overlap each other
  tapestry.php
  templates/single-tapestry.php
  templates/vue/src/components/NodeModal.vue
Labels: ready for review

#618 612 - Add progress support for non-logged-in users
  classes/class.tapestry-user-progress.php
  templates/tapestry.js
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/store/actions.js
Labels: needs testing
