Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-08, with the labels that each got.

#669 668 - Optimize path calculation function for improved speed
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  endpoints.php
  utilities/class.tapestry-cache.php
Labels: ready to merge

#570 566 - Submit button should be disabled while any file is uploading
  templates/vue/package.json
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
Labels: ready for review

#667 655 - WordPress posts only search within the first 10 posts
  templates/vue/src/components/node-modal/content-form/WpPostForm.vue
  templates/vue/src/services/WordpressApi.js
Labels: ready for review

#651 650- WordPress content titles become distorted in Tapestry
  tapestry.php
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/lightbox/WpPostMedia.vue
  templates/vue/src/components/node-modal/content-form/WpPostForm.vue
Labels: ready for review

#657 656 - Bug fix: Duplicated Tapestry name reverts when Tapestry is modified
  classes/class.tapestry.php
Labels: ready for review

#665 663 - Bug Fix: Tapestry disappears when lightbox is opened after filter
  templates/tapestry.js
  templates/vue/src/components/TapestryFilter.vue
Labels: ready for review

#676 675 - Bug fix: Remove "Add Tapestry" button for non-admins
  tapestry.php
Labels: ready to merge

#659 658 - [TYDE] Bug fix: Tapestry crashes if there is a stage with mixed topics
  classes/class.tapestry.php
  templates/vue/src/components/TapestryMedia.vue
Labels: ready for review

#539 538 - Allow author to add copyright and references for each node
  classes/class.tapestry-node.php
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/node-modal/MoreInformationForm.vue
  templates/vue/src/store/getters.js
  templates/vue/src/utils/constants.js
Labels: ready to merge

#537 536 - Show a sidebar when selecting a node
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/App.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryIcon.vue
  templates/vue/src/components/TapestrySidebar.vue
  templates/vue/src/utils/Helpers.js
Labels: ready to merge

#666 664 - Keep node authors on import
  classes/class.tapestry-node.php
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#512 509 - Update Cypress tests so we can run them individually or in portions
  .gitignore
  docker/docker-compose.yml
  templates/e2e/cypress-sample.json
  templates/e2e/cypress.json
  templates/e2e/cypress/fixtures/example.json
  templates/e2e/cypress/fixtures/root.json
  templates/e2e/cypress/fixtures/two-nodes.json
  templates/e2e/cypress/fixtures/user.json
  templates/e2e/cypress/integration/authoring/appearance.spec.js
  templates/e2e/cypress/integration/authoring/content.spec.js
  templates/e2e/cypress/integration/authoring/management.spec.js
  templates/e2e/cypress/integration/authoring/permissions.spec.js
  templates/e2e/cypress/integration/user.spec.js
  templates/e2e/cypress/plugins/index.js
  templates/e2e/cypress/screenshots/authoring.spec.js.zip
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to add and see a root node (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to add child nodes (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to delete a leaf node (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open add modal (failed) (1).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open add modal (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Basic node management -- Should be able to open edit modal (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should be able to open lightbox by clicking on center of node if media button is hidden (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide media button (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide node title (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should hide progress bar (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node appearance -- Should show a thumbnail if a thumbnail url is passed (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a Gravity Form and have the form be visible (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a quiz to a video and have that quiz appear at the end of the video (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a text node and verify that the text matches what was entered (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add a video url and length and have the video load (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Media types -- Should be able to add an external link node and have it show a summary of the external page (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node content -- Should be able to edit content fields and see the changes applied (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide add button if user does not have add access (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide edit button if user does not have write access (failed).png
  templates/e2e/cypress/screenshots/authoring.spec.js/Authoring -- Node permissions -- Should hide node and associated links if user does not have read access (failed).png
  templates/e2e/cypress/support/commands.js
  templates/e2e/cypress/support/index.js
  templates/e2e/cypress/support/roles.js
  templates/e2e/cypress/support/utils.js
  templates/e2e/cypress/videos/authoring.spec.js.mp4
  templates/e2e/cypress/videos/user.spec.js.mp4
  templates/vue/.gitignore
  templates/vue/cypress-sample.json
  templates/vue/cypress/integration/author.spec.js
  templates/vue/cypress/integration/user.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/utils.js
  templates/vue/package.json
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
  templates/vue/src/components/node-modal/content-form/ActivityForm.vue
  templates/vue/src/components/node-modal/content-form/GravityFormForm.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
Labels: ready to merge

#672 671 - Bug Fix: Tapestry reloads when the settings modal opens
  classes/class.tapestry.php
  templates/vue/src/components/SettingsModal.vue
Labels: ready to merge

#693 687 - Bug fix: Tapestry max depth is calculated incorrectly
  templates/tapestry.js
Labels: needs testing
