Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-05, with the labels that each got.

#399 Show teen's progress if user is a copilot
  classes/class.tapestry-form.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  endpoints.php
  interfaces/interface.tapestry-form.php
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/Tyde.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/GravityForm.vue
  templates/vue/src/components/lightbox/QuizMedia.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/tyde/TydeActivitySummary.vue
  templates/vue/src/components/tyde/TydeMenu.vue
  templates/vue/src/components/tyde/TydeModuleSummary.vue
  templates/vue/src/components/tyde/TydeSpaceshipPart.vue
  templates/vue/src/components/tyde/TydeStage.vue
  templates/vue/src/components/tyde/TydeTopic.vue
  templates/vue/src/services/GravityFormsApi.js
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
Labels: ready for review

#475 TYDE: Add custom audio recorder
  README.md
  classes/class.tapestry-audio.php
  classes/class.tapestry-form.php
  classes/class.tapestry-user-progress.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/package.json
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryActivity.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/QuizScreen.vue
  templates/vue/src/components/lightbox/TextMedia.vue
  templates/vue/src/components/lightbox/quiz-screen/CompletionScreen.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/node-modal/QuizModal.vue
  templates/vue/src/components/tyde/TydeActivitySummary.vue
  templates/vue/src/services/GravityFormsApi.js
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
Labels: TYDE, ready to merge

#424 Add custom audio recorder
  classes/class.tapestry-audio.php
  classes/class.tapestry-user-progress.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  templates/tapestry.js
  templates/vue/package.json
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryActivity.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/quiz-screen/CompletionScreen.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/node-modal/QuizModal.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
Labels: ready to merge

#461 Show special icon for activity as well in accordion row
  templates/vue/src/components/lightbox/AccordionMedia.vue
Labels: ready for review

#402 Fix H5P settings not being saved correctly
  classes/class.tapestry-user-progress.php
  endpoints.php
  templates/tapestry.js
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/utils/Helpers.js
Labels: ready to merge

#480 TYDE: Fix H5P settings not being saved correctly
  classes/class.tapestry-user-progress.php
  endpoints.php
  templates/tapestry.js
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/utils/Helpers.js
Labels: ready for review

#465 Fixed issue with unchecking lock nodes checklist
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
Labels: ready for review

#463 If a parent node has a certain permission, its children should be limited to that permission too
  classes/class.tapestry.php
  templates/tapestry.js
  templates/vue/src/components/Tapestry.vue
Labels: ready for review

#488 Fix audio recorder build error
  templates/vue/webpack.config.js
Labels: ready to merge

#491 TYDE: Fix audio recorder build error
  templates/vue/webpack.config.js
Labels: ready for review

#450 Fix accordion not auto scrolling for some content types
  templates/libs/h5p-resizer.min.js
  templates/single-tapestry.php
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/ExternalMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
Labels: ready to merge

#470 Fix videos getting clipped in some cases
  classes/class.tapestry-node.php
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
Labels: ready to merge

#496 Made tooltip styling more cross-browser compatible
  templates/tapestry.css
  templates/tapestry.js
Labels: ready to merge

#497 TYDE: Made tooltip styling more cross-browser compatible
  templates/tapestry.css
  templates/tapestry.js
Labels: ready for review

#503 Add ability to filter nodes based on certain attributes
  classes/class.tapestry-node.php
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/App.vue
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/components/lightbox/GravityForm.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/store/actions.js
Labels: ready to merge

#489 TYDE: Fix accordion not auto scrolling for some content types
  templates/libs/h5p-resizer.min.js
  templates/single-tapestry.php
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/ExternalMedia.vue
  templates/vue/src/components/lightbox/GravityForm.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
  templates/vue/src/services/LinkPreviewApi.js
Labels: ready for review

#490 TYDE: Fix videos getting clipped in some cases
  classes/class.tapestry-node.php
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
Labels: ready for review

#492 Fix play screen showing on rewatch and h5p not resizing correctly
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
Labels: ready to merge

#507 TYDE: Fix play screen showing on rewatch and h5p not resizing correctly
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
Labels: ready for review

#504 TYDE: Add ability to filter nodes based on certain attributes
  classes/class.tapestry-node.php
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/App.vue
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/store/actions.js
Labels: ready for review

#486 Add new locking conditions based on date
  templates/libs/moment-timezone-with-data-2015-2025.js
  templates/libs/moment.min.js
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/package.json
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/utils/constants.js
Labels: ready to merge

#515 TYDE: Add new locking conditions based on date
  templates/libs/moment-timezone-with-data-2015-2025.js
  templates/libs/moment.min.js
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/package.json
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/utils/constants.js
Labels: ready for review

#474 Default Node Permissions and Access Tab Control
  classes/class.tapestry-node.php
  templates/single-tapestry.php
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  utilities/class.tapestry-node-permissions.php
Labels: ready for review

#517 Deleting Child Nodes Causes Node to Become Uneditable
  templates/tapestry.js
  templates/vue/src/store/mutations.js
Labels: ready for review

#514 TYDE: Allow Reordering of Topics In Stage
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/tyde/TydeStage.vue
  templates/vue/src/store/mutations.js
Labels: needs testing
