Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-10, with the labels that each got.

#731 730 - Bug fix: Tapestry Depth setting showing incorrect max depth
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/SettingsModalButton.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryDepthSlider.vue
Labels: ready for review

#732 760 - Bug fix: YouTube video in accordion appears outside of accordion
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/YouTubeMedia.vue
Labels: ready for review

#774 773 - Bug Fix: Update external media background to white
  templates/vue/src/components/lightbox/ExternalMedia.vue
Labels: ready to merge

#624 623 - Extend Vue Router
  templates/vue/.eslintrc.js
  templates/vue/src/App.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/LockedTooltip.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/SettingsModalButton.vue
  templates/vue/src/components/TapestryAccordion.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryDepthSlider.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/TapestrySidebar.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
  templates/vue/src/components/node-modal/DeleteNodeButton.vue
  templates/vue/src/components/node-modal/content-form/RichTextForm.vue
  templates/vue/src/components/tapestry-node/AddChildButton.vue
  templates/vue/src/config/routes.js
  templates/vue/src/router.js
  templates/vue/src/store/getters.js
Labels: ready to merge

#776 775 - Update TapestryNode to use relative coordinates
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/tapestry-node/AddChildButton.vue
  templates/vue/src/components/tapestry-node/ProgressBar.vue
Labels: ready to merge

#781 780 - Bug fix: Root node button not opening node modal
  templates/vue/src/components/TapestryApp.vue
Labels: ready for review

#770 769 - creating slack mention workflow
  .github/mention-to-slack.yml
  .github/workflows/mention-to-slack.yml
Labels: needs work

#756 740 - Bug fix: H5P video in accordion appearing cutoff height-wise
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/YouTubeMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
Labels: ready to merge

#783 782 - Bug fix: Zero depth makes all nodes grandchild nodes
  templates/vue/src/components/TapestryDepthSlider.vue
Labels: ready for review

#790 789 - Bug fix: Links are displaying in the wrong place when dragging
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/tapestry-node/AddChildButton.vue
Labels: ready to merge

#758 753 - Fix and Improve WP Init Script
  .gitignore
  Makefile
  bin/await-containers.sh
  bin/config-sample.sh
  bin/install.sh
  bin/node-install.sh
  bin/setup-env.sh
  bin/stop-app.sh
  templates/vue/.gitignore
  templates/vue/config-sample.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/services/LinkPreviewApi.js
  templates/vue/webpack.config.js
Labels: ready to merge

#678 674 - accept/reject: Add private nodes to a tapestry that only I have access to
  classes/class.tapestry-node.php
  classes/class.tapestry.php
  endpoints.php
  templates/single-tapestry.php
  templates/vue/.eslintignore
  templates/vue/__tests__/App.test.js
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/tapestry-node/ProgressBar.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/Helpers.js
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#771 748 - Bug Fix: Node not displaying after changing connections
  classes/class.tapestry.php
Labels: ready to merge

#787 786 - Bug fix: Depth slider icons appear out of place on smaller screens
  templates/vue/src/components/TapestryDepthSlider.vue
  templates/vue/src/components/TapestryIcon.vue
Labels: ready for review

#682 652 - enhance duplication and import/export
  classes/class.tapestry-node.php
  classes/class.tapestry.php
  endpoints.php
  tapestry.php
  templates/single-tapestry.php
  templates/vue/src/components/ImportChangelog.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/settings-modal/DuplicateTapestryButton.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/getters.js
Labels: ready for review

#745 738 - Public users should not be able to add or edit
  endpoints.php
  templates/vue/src/components/TapestryLink.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/wp.js
Labels: ready for review

#762 759 - Remove autogenerated thumbnail fix
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
Labels: needs testing

#808 807 - fix permission table checkbox disabling
  templates/vue/src/components/node-modal/PermissionsTable.vue
Labels: needs testing

#803 802 - Bug Fix: DragSelect activates while adjusting depth slider
  templates/vue/src/components/TapestryDepthSlider.vue
  templates/vue/src/utils/dragSelectModular.js
Labels: ready for review

#794 793 - Bug Fix: Remove editor from permissions
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  utilities/class.tapestry-node-permissions.php
Labels: ready for review

#779 777 - Update Cypress to work with new master
  templates/vue/cypress/integration/authoring/appearance.spec.js
  templates/vue/cypress/integration/authoring/content.spec.js
  templates/vue/cypress/integration/authoring/management.spec.js
  templates/vue/cypress/integration/authoring/permissions.spec.js
  templates/vue/cypress/integration/user.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/utils.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/tapestry-node/AddChildButton.vue
Labels: ready for review

#815 813 - Bug Fix: Logged in users are allowed to delete links that dismember part of the tapestry
  templates/vue/src/components/TapestryLink.vue
Labels: ready for review

#820 818 - admin private nodes are not hidden
  classes/class.tapestry.php
  config/php.conf.ini
  templates/vue/src/utils/dataset.js
Labels: ready to merge

#797 796 - Disable autofill for filter
  templates/vue/src/components/Combobox.vue
  templates/vue/src/components/TapestryFilter.vue
Labels: ready for review

#784 670 - Add coverage report and Cypress enhancements
  templates/vue/.babelrc
  templates/vue/README.md
  templates/vue/babel.config.json
  templates/vue/cypress/integration/authoring/content.spec.js
  templates/vue/cypress/integration/authoring/management.spec.js
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/cypress/integration/link-authoring.spec.js
  templates/vue/cypress/integration/media-types/accordion.spec.js
  templates/vue/cypress/integration/media-types/embed.spec.js
  templates/vue/cypress/integration/navigation.spec.js
  templates/vue/cypress/integration/node-appearance.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/node-locked.spec.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/cypress/integration/node-permissions.spec.js
  templates/vue/cypress/plugins/index.js
  templates/vue/cypress/support/index.js
  templates/vue/jest.config.js
  templates/vue/package-lock.json
  templates/vue/package.json
Labels: ready to merge

#832 831 - fix link deletions for private drafts
  endpoints.php
Labels: ready to merge

#791 788 - Add missing Cypress tests to achieve better coverage
  docker-compose.yml
  templates/vue/.eslintrc.js
  templates/vue/cypress-sample.json
  templates/vue/cypress/fixtures/accordion.json
  templates/vue/cypress/fixtures/example.json
  templates/vue/cypress/fixtures/one-node.json
  templates/vue/cypress/fixtures/reddit.png
  templates/vue/cypress/fixtures/three-nodes.json
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/cypress/integration/lightbox/accordion.spec.js
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/cypress/integration/lightbox/embed.spec.js
  templates/vue/cypress/integration/lightbox/video.spec.js
  templates/vue/cypress/integration/lightbox/wordpress.spec.js
  templates/vue/cypress/integration/link-authoring.spec.js
  templates/vue/cypress/integration/media-types/embed.spec.js
  templates/vue/cypress/integration/node-appearance.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/node-locked.spec.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/cypress/integration/node-permissions.spec.js
  templates/vue/cypress/integration/settings.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/constants.js
  templates/vue/cypress/support/index.js
  templates/vue/cypress/support/utils.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/FileUpload.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/SettingsModalButton.vue
  templates/vue/src/components/TapestryLink.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/__tests__/Lightbox.spec.js
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/PlayScreen.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/components/node-modal/PermissionsTable.vue
  templates/vue/src/components/node-modal/content-form/TextForm.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
  templates/vue/src/components/node-modal/content-form/WpPostForm.vue
  templates/vue/src/components/settings-modal/DuplicateTapestryButton.vue
  templates/vue/src/components/settings-modal/__tests__/DuplicateTapestryButton.spec.js
  templates/vue/src/fixtures/one-node.json
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
Labels: ready for review
