Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-09, with the labels that each got.

#715 714 - Upgrade to Babel 7
  templates/vue/.babelrc
  templates/vue/.eslintignore
  templates/vue/babel.config.json
  templates/vue/config/webpack.base.js
  templates/vue/config/webpack.dev.js
  templates/vue/config/webpack.prod.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/main.js
  templates/vue/webpack.config.js
Labels: needs testing

#697 696 - Remove nodes that are not in links from dataset in frontend
  templates/tapestry.js
Labels: ready to merge

#688 686 - Bug fix: Progress bar is invisible on H5P content
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
Labels: ready to merge

#685 684 - Bug fix: Tapestry nodes displaying oddly after a refresh when a node is open
  templates/vue/src/components/lightbox/H5PMedia.vue
Labels: ready to merge

#706 701 - Improve Docker configuration
  .env
  .githooks/pre-commit
  .gitignore
  Makefile
  bin/install.sh
  bin/start.sh
  config/php.conf.ini
  docker-compose.yml
  docker/Dockerfile
  docker/docker-compose.yml
  docker/wp-config-sample.php
  docker/wp-init.sh
  tapestry.code-workspace
  templates/vue/.babelrc
  templates/vue/.eslintignore
  templates/vue/Dockerfile
  templates/vue/babel.config.json
  templates/vue/config/webpack.base.js
  templates/vue/config/webpack.dev.js
  templates/vue/config/webpack.prod.js
  templates/vue/cypress-sample.json
  templates/vue/cypress/fixtures/example.json
  templates/vue/cypress/fixtures/root.json
  templates/vue/cypress/fixtures/two-nodes.json
  templates/vue/cypress/fixtures/user.json
  templates/vue/cypress/integration/authoring/appearance.spec.js
  templates/vue/cypress/integration/authoring/content.spec.js
  templates/vue/cypress/integration/authoring/management.spec.js
  templates/vue/cypress/integration/authoring/permissions.spec.js
  templates/vue/cypress/integration/user.spec.js
  templates/vue/cypress/plugins/index.js
  templates/vue/cypress/support/commands.js
  templates/vue/cypress/support/index.js
  templates/vue/cypress/support/roles.js
  templates/vue/cypress/support/utils.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/main.js
  templates/vue/webpack.config.js
Labels: ready for review

#710 [No ticket] Bug fix: hide search button for non-admins
  templates/vue/src/components/TapestryFilter.vue
Labels: ready to merge

#690 689 - Bug fix: Formattable text area list is double spaced
  templates/tapestry.css
Labels: ready to merge

#660 654 - Be told if my system, browser, or resolution does not meet the requirements
  tapestry.php
  templates/libs/es2015-test.js
  templates/single-tapestry.php
Labels: needs testing

#724 723 - Bug fix: Fix forbidden error on node additions
  templates/vue/src/components/NodeModal.vue
Labels: needs testing

#722 [No ticket] Fix hot reload not working in 482
  templates/vue/config/webpack.dev.js
Labels: ready for review

#744 743 - Bug fix: Pressing cancel on the Add Tapestry pop-up still creates tapestry
  tapestry.php
Labels: ready to merge

#761 741 - Unable to open the settings modal more than one time
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/SettingsModalButton.vue
Labels: ready for review

#735 734 - enforce full height iframes
  templates/vue/src/components/SettingsModalButton.vue
  templates/vue/src/components/lightbox/ExternalMedia.vue
Labels: ready for review

#747 746 - Bug fix: Adding child node makes it appear like a grandchild node
  templates/vue/src/components/TapestryDepthSlider.vue
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/constants.js
Labels: ready for review

#749 736 - Bug fix: control+A selection doesn't work in node modal
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/utils/dragSelectModular.js
Labels: ready to merge

#750 739 - cannot select new nodes
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/utils/dragSelectModular.js
Labels: ready to merge
