Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-06, with the labels that each got.

#549 Improve H5P and Lightbox responsiveness
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/tyde/TydeStage.vue
  templates/vue/src/components/tyde/TydeTopic.vue
Labels: ready to merge

#501 Refactor accordion for better reusability
  templates/vue/src/components/AccordionRow.vue
  templates/vue/src/components/TapestryAccordion.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
Labels: ready for review

#502 TYDE: Refactor accordion for better reusability
  templates/vue/src/components/AccordionRow.vue
  templates/vue/src/components/TapestryAccordion.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
Labels: ready for review

#499 Show favourites in spaceship cockpit
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/TapestryModal.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/GravityForm.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/QuizMedia.vue
  templates/vue/src/components/lightbox/QuizScreen.vue
  templates/vue/src/components/lightbox/TextMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
  templates/vue/src/components/lightbox/accordion/SubAccordion.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/tyde/TydeFavourites.vue
  templates/vue/src/components/tyde/TydeMenu.vue
  templates/vue/src/components/tyde/TydeModuleSummary.vue
  templates/vue/src/components/tyde/tyde-favourites/TydeFavouritesRow.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/store/index.js
Labels: ready for review

#550 Master: Improve H5P and Lightbox responsiveness
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
Labels: ready for review

#546 Add analytics (TYDE)
  endpoints.php
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/.eslintrc.js
  templates/vue/src/components/AudioRecorder.vue
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Tyde.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/EndScreen.vue
  templates/vue/src/components/lightbox/GravityForm.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/lightbox/QuizScreen.vue
  templates/vue/src/components/lightbox/VideoMedia.vue
  templates/vue/src/components/lightbox/quiz-screen/CompletionScreen.vue
  templates/vue/src/components/lightbox/quiz-screen/Question.vue
  templates/vue/src/components/tyde/TydeButton.vue
  templates/vue/src/components/tyde/TydeModule.vue
  templates/vue/src/components/tyde/TydeStage.vue
  templates/vue/src/components/tyde/TydeTopic.vue
Labels: ready for review

#479 Add Youtube support and auto-calculate video length for all videos
  templates/vue/config-sample.js
  templates/vue/package.json
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/YoutubeMedia.vue
  templates/vue/src/main.js
  templates/vue/src/utils/Helpers.js
Labels: ready to merge

#528 TYDE: Upgrade Eslint to 7.1.0
  templates/vue/package.json
Labels: ready for review

#529 Upgrade Eslint to 7.1.0
  templates/vue/package.json
Labels: ready for review

#493 Do not return locked node content until node is actually unlocked
  classes/class.constants.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  templates/tapestry.js
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/QuizMedia.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  utilities/class.tapestry-user-roles.php
Labels: ready to merge

#508 Allow tapestry import/export/duplicate
  classes/class.tapestry-node.php
  endpoints.php
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/settings-modal/DuplicateTapestryButton.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/getters.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-permissions.php
Labels: tyde pr needed

#535 Containerize Application With Docker
  .gitattributes
  .gitignore
  docker/Dockerfile
  docker/docker-compose.yml
  docker/upload.ini
  docker/wp-config-sample.php
  docker/wp-init.sh
  templates/vue/Dockerfile
  templates/vue/package.json
  templates/vue/webpack.config.js
Labels: ready for review

#560 TYDE: Containerize Application with Docker
  .gitattributes
  .gitignore
  docker/Dockerfile
  docker/docker-compose.yml
  docker/upload.ini
  docker/wp-config-sample.php
  docker/wp-init.sh
  templates/vue/Dockerfile
  templates/vue/package.json
  templates/vue/webpack.config.js
Labels: ready for review

#526 TYDE: Add Youtube support and auto-calculate video length for all videos
  templates/vue/config-sample.js
  templates/vue/package.json
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/YouTubeMedia.vue
  templates/vue/src/main.js
  templates/vue/src/utils/Helpers.js
Labels: needs testing

#571 Fix H5P Modal Switching and Infinite H5P Load
  templates/vue/src/components/NodeModal.vue
Labels: needs testing

#563 Fix tooltip sometimes covering parts of the UI
  templates/tapestry.css
  templates/tapestry.js
Labels: ready to merge

#568 TYDE: Allow tapestry import/export/duplicate
  classes/class.tapestry-node.php
  endpoints.php
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/settings-modal/DuplicateTapestryButton.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/getters.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-permissions.php
Labels: ready for review

#561 Add PHP linter
  .githooks/pre-commit
  classes/class.tapestry-audio.php
  classes/class.tapestry-form.php
  classes/class.tapestry-group.php
  classes/class.tapestry-h5p.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  interfaces/interface.tapestry-form.php
  interfaces/interface.tapestry-group.php
  interfaces/interface.tapestry-h5p.php
  interfaces/interface.tapestry-node.php
  interfaces/interface.tapestry-user-progress.php
  interfaces/interface.tapestry.php
  tapestry.php
  templates/single-tapestry.php
  templates/vue/.vscode/extensions.json
  templates/vue/.vscode/settings.json
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-node-permissions.php
  utilities/class.tapestry-permissions.php
  utilities/class.tapestry-user-roles.php
Labels: ready to merge

#578 TYDE: Add PHP linter
  .githooks/pre-commit
  classes/class.tapestry-audio.php
  classes/class.tapestry-form.php
  classes/class.tapestry-group.php
  classes/class.tapestry-h5p.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  docker/wp-config-sample.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  interfaces/interface.tapestry-form.php
  interfaces/interface.tapestry-group.php
  interfaces/interface.tapestry-h5p.php
  interfaces/interface.tapestry-node.php
  interfaces/interface.tapestry-user-progress.php
  interfaces/interface.tapestry.php
  tapestry.php
  templates/single-tapestry.php
  templates/vue/src/components/TapestryMedia.vue
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-node-permissions.php
  utilities/class.tapestry-permissions.php
  utilities/class.tapestry-user-roles.php
Labels: ready for review

#592 [No ticket] Fix author check not working correctly
  templates/tapestry.js
Labels: ready for review

#532 531 - Improve NodeModal.vue and Tapestry.vue code structures
  templates/tapestry.js
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Loading.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
  templates/vue/src/components/node-modal/BehaviourForm.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/components/node-modal/content-form/AccordionForm.vue
  templates/vue/src/components/node-modal/content-form/ActivityForm.vue
  templates/vue/src/components/node-modal/content-form/GravityFormForm.vue
  templates/vue/src/components/node-modal/content-form/H5pForm.vue
  templates/vue/src/components/node-modal/content-form/TextForm.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
  templates/vue/src/components/node-modal/content-form/WpPostForm.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/constants.js
Labels: ready to merge

#543 Ensure password protection works for tapestries
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.js
Labels: ready to merge

#547 [No ticket] Change linter output to include what errors were found
  templates/vue/lint.js
Labels: ready to merge

#555 Various improvements for TYDE (as part of release)
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.css
  templates/tapestry.js
  templates/vue/src/App.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/H5PIframe.vue
  templates/vue/src/components/lightbox/H5PMedia.vue
  templates/vue/src/components/tyde/TydeButton.vue
  templates/vue/src/components/tyde/TydeCockpit.vue
  templates/vue/src/components/tyde/TydeMenu.vue
  templates/vue/src/components/tyde/TydeMenuHelp.vue
Labels: ready to merge

#573 Various improvements for master
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/src/App.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/lightbox/AccordionMedia.vue
Labels: ready for review

#582 577 - Node selection interferes with the depth slider
  templates/tapestry.js
Labels: ready to merge

#541 540 - Change external link to open in new tab by default
  classes/class.constants.php
  classes/class.tapestry-node.php
  docker/wp-config-sample.php
  endpoints.php
  tapestry.php
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/store/getters.js
  utilities/class.tapestry-user-roles.php
Labels: ready for review

#576 Fix Import Statment Causing Docker Compliation Failure
  templates/vue/src/components/TapestryMedia.vue
  templates/vue/src/components/lightbox/YouTubeMedia.vue
Labels: ready for review

#608 [No Ticket] Fix bugs revolving around two Tapestry instances
  tapestry.php
  templates/single-tapestry.php
Labels: ready for review

#575 TYDE: Fix Import Statment Causing Docker Compliation Failure
  templates/vue/src/components/TapestryMedia.vue
Labels: ready for review

#534 533 - If user is able to add/edit, they should automatically be able to view that node too
  classes/class.tapestry.php
  templates/vue/src/components/node-modal/PermissionsTable.vue
Labels: ready for review

#552 551 - Add support for "Column" H5P content
  templates/vue/src/components/lightbox/H5PIframe.vue
Labels: ready for review

#590 [No ticket] Fix accordion rows closing on their own on first watch
  templates/vue/src/store/actions.js
  templates/vue/src/store/mutations.js
Labels: ready for review

#609 [No ticket] Fix copilots not being able to submit activities
  templates/vue/src/components/lightbox/GravityForm.vue
Labels: ready for review

#558 557 - Show error and prevent submission when file upload fails
  templates/vue/src/components/FileUpload.vue
Labels: ready for review

#572 TYDE: 531 - Improve NodeModal.vue and Tapestry.vue code structures
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/src/components/Lightbox.vue
  templates/vue/src/components/Loading.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/RootNodeButton.vue
  templates/vue/src/components/Tapestry.vue
  templates/vue/src/components/node-modal/AppearanceForm.vue
  templates/vue/src/components/node-modal/BehaviourForm.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/components/node-modal/SpaceshipPartForm.vue
  templates/vue/src/components/node-modal/content-form/AccordionForm.vue
  templates/vue/src/components/node-modal/content-form/ActivityForm.vue
  templates/vue/src/components/node-modal/content-form/GravityFormForm.vue
  templates/vue/src/components/node-modal/content-form/H5pForm.vue
  templates/vue/src/components/node-modal/content-form/TextForm.vue
  templates/vue/src/components/node-modal/content-form/TydeTypeInput.vue
  templates/vue/src/components/node-modal/content-form/UrlEmbedForm.vue
  templates/vue/src/components/node-modal/content-form/VideoForm.vue
  templates/vue/src/components/node-modal/content-form/WpPostForm.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/constants.js
Labels: ready for review

#567 TYDE: 485 - Do not return locked node content until node is actually unlocked
  classes/class.constants.php
  classes/class.tapestry-audio.php
  classes/class.tapestry-form.php
  classes/class.tapestry-group.php
  classes/class.tapestry-h5p.php
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  classes/class.tapestry.php
  docker/wp-config-sample.php
  endpoints.php
  interfaces/interface.tapestry-audio.php
  interfaces/interface.tapestry-form.php
  interfaces/interface.tapestry-group.php
  interfaces/interface.tapestry-h5p.php
  interfaces/interface.tapestry-node.php
  interfaces/interface.tapestry-user-progress.php
  interfaces/interface.tapestry.php
  tapestry.php
  templates/single-tapestry.php
  templates/tapestry.js
  templates/vue/src/components/lightbox/AccordionMedia.vue
  templates/vue/src/components/lightbox/QuizMedia.vue
  templates/vue/src/components/node-modal/ConditionsForm.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-node-permissions.php
  utilities/class.tapestry-permissions.php
  utilities/class.tapestry-user-roles.php
Labels: ready to merge

#610 [No ticket] Bug fix: Duplicate Advanced tabs in TYDE settings and lint errors
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/store/actions.js
Labels: ready for review
