Repository tapestry-tool/tapestry-wp, pull requests merged in 2020-12, with the labels that each got.

#861 859 - Allow App-Stop Script to Work when Browser is Loading Webpack Content
  bin/stop-app.sh
Labels: ready for review

#880 879 - Flaky Test: "should be able to submit a node and have it be accepted"
  templates/vue/cypress/integration/review.spec.js
Labels: ready for review

#884 883 - Remove obsolete "Users can move nodes" setting
  classes/class.tapestry.php
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/utils/test.js
Labels: ready for review

#876 868 - Bug Fix: Superadmins should have full edit rights on all sites
  classes/class.tapestry-group.php
  classes/class.tapestry.php
  endpoints.php
  utilities/class.tapestry-helpers.php
  utilities/class.tapestry-user-roles.php
  utilities/class.tapestry-user.php
Labels: needs testing

#878 877 - Dev: Add Bundle Analyzer package for helping with optimization
  templates/vue/config/webpack.dev.js
  templates/vue/package-lock.json
  templates/vue/package.json
Labels: ready to merge

#893 887 - Changing the description for a node to be 2000 characters
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/node-modal/ContentForm.vue
  templates/vue/src/components/node-modal/content-form/RichTextForm.vue
Labels: ready for review

#892 885 - Bug fix: edit modal doesn't populate on refresh
  templates/vue/src/components/NodeModal.vue
Labels: ready for review

#891 890 - Only allow selection and moving of editable nodes
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/utils/dragSelectModular.js
Labels: ready to merge

#846 768/841 - Show errors when submitting a node with invalid video or if there are backend errors
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/TapestryError.vue
  templates/vue/src/store/actions.js
  templates/vue/src/store/index.js
  templates/vue/src/store/mutations.js
Labels: ready to merge

#906 905 - Update linter to run on Cypress files
  templates/vue/cypress/integration/lightbox/accordion.spec.js
  templates/vue/cypress/integration/lightbox/video.spec.js
  templates/vue/cypress/integration/node-appearance.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/tapestry-map.spec.js
  templates/vue/lint.js
Labels: ready for review

#896 894 - Prompt user when exiting Node Modal with unsaved changes
  templates/vue/cypress/fixtures/accordion.json
  templates/vue/cypress/fixtures/one-node.json
  templates/vue/cypress/fixtures/three-nodes.json
  templates/vue/cypress/fixtures/two-nodes.json
  templates/vue/cypress/fixtures/user.json
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/fixtures/one-node.json
  templates/vue/src/utils/Helpers.js
Labels: ready for review

#900 899 - Bug Fix: Background for tapestries do not load after refresh
  templates/vue/cypress/integration/settings.spec.js
  templates/vue/src/components/TapestryApp.vue
Labels: ready for review

#847 792 - Improve search bar UX and allow searching by title
  classes/class.tapestry.php
  templates/vue/__mocks__/styleMock.js
  templates/vue/config/jest-setup.js
  templates/vue/config/webpack.base.js
  templates/vue/cypress/fixtures/multi-author.json
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/cypress/integration/search-bar.spec.js
  templates/vue/cypress/integration/settings.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/jsconfig.json
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/App.vue
  templates/vue/src/components/NodeModal.vue
  templates/vue/src/components/SettingsModal.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryFilter.vue
  templates/vue/src/components/TapestryNode.vue
  templates/vue/src/components/__tests__/TapestryFilter.spec.js
  templates/vue/src/components/node-modal/ReviewForm.vue
  templates/vue/src/components/node-modal/__tests__/ReviewForm.spec.js
  templates/vue/src/components/tapestry-node/StatusBar.vue
  templates/vue/src/fixtures/multi-author.json
  templates/vue/src/main.js
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/constants.js
  templates/vue/src/utils/test.js
Labels: ready for review

#908 907 - Bug fix: Depth slider not appearing for non-admins
  templates/vue/src/components/SettingsModalButton.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/TapestryDepthSlider.vue
Labels: ready to merge
