Repository tapestry-tool/tapestry-wp, pull requests merged in 2021-08, with the labels that each got.

#1058 1032 - Add drag and drop answer type for Activity node type
  classes/class.tapestry-user-progress.php
  endpoints.php
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/src/assets/icons/drag_drop.svg
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/AnswerButton.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/AudioQuestion.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/DragDropQuestion/Bucket.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/DragDropQuestion/Item.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/DragDropQuestion/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/TextQuestion.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/index.vue
  templates/vue/src/components/Lightbox/media/H5PMedia.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/DragDrop/Bucket.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/DragDrop/Item.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/DragDrop/index.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/index.vue
  templates/vue/src/components/common/TapestryIcon.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/Bucket.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/Item.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/MultipleChoiceForm/ChoiceRow.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/MultipleChoiceForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/components/modals/common/ColorPicker.vue
  templates/vue/src/services/TapestryAPI.js
Labels: ready to merge

#1064 1061 - TYDE2 - Add TYDE Mode
  templates/vue/package-lock.json
  templates/vue/src/App.vue
  templates/vue/src/assets/icons/tyde/cos-unselected.svg
  templates/vue/src/assets/icons/tyde/cos.svg
  templates/vue/src/assets/icons/tyde/goals-unselected.svg
  templates/vue/src/assets/icons/tyde/goals.svg
  templates/vue/src/assets/icons/tyde/profile-unselected.svg
  templates/vue/src/assets/icons/tyde/profile.svg
  templates/vue/src/assets/icons/tyde/tyde-unselected.svg
  templates/vue/src/assets/icons/tyde/tyde.svg
  templates/vue/src/components/Lightbox/TapestryModal/index.vue
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/modals/SettingsModal/index.vue
  templates/vue/src/components/tyde/Navbar.vue
  templates/vue/src/components/tyde/TydeIcon.vue
Labels: ready to merge

#1093 1092 - TYDE 2 - Add ability to delete connections
  classes/activities/class.circle-of-support.php
  endpoints.php
  endpoints/endpoints.circle-of-support.php
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/index.vue
  templates/vue/src/services/TapestryAPI.js
Labels: needs final review

#1072 1067 - TYDE2 - migrate community view onboarding
  templates/vue/config/webpack.base.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/assets/styles/onbording-colors.scss
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosModal.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/AddConfirmation.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/ObFinishView.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/Tooltip.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/WelcomeCommunities.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/WelcomeConnections.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/onboarding.config.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/onboardingMachine.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/SingleConnection.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/index.vue
Labels: ready to merge

#1075 1073 - Change emoji selector to allow skin colour selection
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddCommunityForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CommunitiesList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/ConnectionsTab.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionTooltip.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/SingleConnection.vue
Labels: needs refactoring, needs work

#1078 1077 - Add ability to reverse link parent-child direction
  classes/class.tapestry.php
  endpoints.php
  templates/vue/cypress/integration/link-authoring.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/package-lock.json
  templates/vue/src/App.vue
  templates/vue/src/components/TapestryMain/TapestryLink.vue
  templates/vue/src/components/modals/LinkModal/index.vue
  templates/vue/src/config/routes.js
  templates/vue/src/router.js
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
  templates/vue/src/store/mutations.js
Labels: ready to merge

#1087 1086 - Show answer when displaying completed activity questions
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/src/components/Lightbox/media/ActivityMedia/AnswerMedia.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
  templates/vue/src/components/Lightbox/media/TapestryMedia.vue
Labels: needs final review

#1080 1079 - Change all lightboxes to have light background with dark text
  templates/vue/src/assets/icons/drag_drop.svg
  templates/vue/src/components/Lightbox/TapestryModal/index.vue
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/AnswerMedia.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/AnswerButton.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/AudioQuestion.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/DragDropQuestion/Item.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/AccordionRows.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageRows.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/common/LockedContent.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/index.vue
  templates/vue/src/components/Lightbox/media/TextMedia.vue
  templates/vue/src/components/Lightbox/media/VideoMedia/EndScreen.vue
  templates/vue/src/components/Lightbox/media/VideoMedia/index.vue
  templates/vue/src/components/Lightbox/media/WpPostMedia.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/CompletedMultipleChoiceItem.vue
  templates/vue/src/components/Lightbox/media/common/CompletedActivityMedia/index.vue
  templates/vue/src/components/common/TapestryIcon/DragDropIcon.vue
  templates/vue/src/components/common/TapestryIcon/index.vue
Labels: ready to merge

#1048 1047 - TYDE2 - Move over CoS and change it to open using icon on toolbar
  classes/activities/class.circle-of-support.php
  endpoints.php
  endpoints/endpoints.circle-of-support.php
  templates/vue/config/webpack.base.js
  templates/vue/cypress/integration/node-operations.spec.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/assets/styles/onbording-colors.scss
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/index.vue
  templates/vue/src/components/modals/SettingsModal/index.vue
  templates/vue/src/components/tyde/Navbar.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleView/CircleToggle.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleView/states.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddCommunityForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddCommunityTab.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CommunitiesList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/ConnectionsList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/ConnectionsTab.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosModal.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosPopup.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosPopupButton.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/AddConfirmation.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/ObFinishView.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/Tooltip.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/WelcomeCommunities.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/WelcomeConnections.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/onboarding.config.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/onboarding/onboardingMachine.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionTooltip.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/ConnectionsList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CosPopup.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CosPopupButton.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/README.md
  templates/vue/src/components/tyde/activities/CircleOfSupport/SingleConnection.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/cos.config.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/index.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/utils/Helpers.js
Labels: needs final review

#1101 1100 - Bug Fix: Fix page navigation in full-screen mode
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/PageMenuItem.vue
Labels: needs final review

#1098 1097 - Automatically enable wordpress debug log on Docker
  docker-compose.yml
Labels: needs final review

#1110 1074 - Save the last selected node for user and select it on load (using router hook)
  classes/class.tapestry-user-progress.php
  endpoints.php
  interfaces/interface.tapestry-user-progress.php
  templates/vue/src/App.vue
  templates/vue/src/router.js
  templates/vue/src/services/TapestryAPI.js
Labels: needs final review
