Repository tapestry-tool/tapestry-wp, pull requests merged in 2021-02, with the labels that each got.

#925 924 - Add abstraction layer between Tapestry and Tyde fixtures
  templates/vue/cypress/support/commands.js
Labels: ready for review

#902 901 - Bug Fix: Subscriber with permissions cannot add
  classes/class.tapestry.php
  endpoints.php
  templates/vue/cypress/fixtures/subscriber-node.json
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/store/actions.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#938 937 - Allow people without edit access to a node to move the node but without saving it
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/TapestryMain/index.vue
Labels: ready to merge

#939 935 - Bug Fix: User node permissions do not render
  classes/class.tapestry.php
  endpoints.php
  templates/vue/cypress/fixtures/subscriber-node.json
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/components/modals/common/PermissionsTable.spec.js
  templates/vue/src/components/modals/common/PermissionsTable.vue
  templates/vue/src/store/actions.js
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#936 934 - Add option in settings to show green halo around accepted nodes
  classes/class.tapestry.php
  templates/vue/src/components/TapestryMain/TapestryNode.spec.js
  templates/vue/src/components/TapestryMain/TapestryNode/StatusBar.vue
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/modals/SettingsModal/index.vue
Labels: ready to merge

#942 941 - Bug fix: Can't see node permissions tab on any node in GEOG 498 tapestry
  templates/vue/src/components/modals/common/PermissionsTable.vue
Labels: ready for review

#895 889 - Add automated testing specific to TYDE
  endpoints.php
  templates/vue/cypress/fixtures/tyde/activities.json
  templates/vue/cypress/fixtures/tyde/one-module.json
  templates/vue/cypress/fixtures/tyde/one-question-set-part-images.json
  templates/vue/cypress/fixtures/tyde/one-question-set.json
  templates/vue/cypress/fixtures/tyde/one-stage.json
  templates/vue/cypress/fixtures/tyde/two-stages.json
  templates/vue/cypress/integration/tyde.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/src/components/common/TapestryModal/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/TydeTypeInput.vue
  templates/vue/src/components/modals/NodeModal/forms/SpaceshipPartForm.vue
  templates/vue/src/components/modals/SettingsModal/index.vue
  templates/vue/src/components/tyde/TydeModule/TydeStage/index.vue
  templates/vue/src/components/tyde/TydeSpaceship/TydeMenu/TydeCockpit/TydeSpaceshipPart.vue
  templates/vue/src/components/tyde/TydeSpaceship/TydeMenu/TydeFavourites/TydeFavouritesRow.vue
  templates/vue/src/components/tyde/TydeSpaceship/TydeMenu/index.vue
  templates/vue/src/components/tyde/TydeSpaceship/index.vue
Labels: ready to merge

#946 940 - Update Setup/Onboarding Documentation
  README.md
Labels: ready to merge

#922 921 - Allow submitted nodes to be moved by the author
  endpoints.php
  templates/vue/package.json
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/modals/NodeModal/DeleteNodeButton.vue
  templates/vue/src/services/__mocks__/wp.js
  templates/vue/src/utils/Helpers.js
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#944 943 - Bug fix: Non-optimized thumbnails being displayed
  classes/class.tapestry-node.php
  tapestry.php
Labels: ready for review

#947 765 - Bug Fix: Old H5P Nodes, When Edited, Show Up as "Video" Content Type
  classes/class.tapestry-node.php
  tapestry-settings.php
  tapestry.php
Labels: ready for review

#957 956 - Bug Fix: Prevent Console Error for Redundant / Duplicate Router Navigation
  templates/vue/src/router.js
Labels: needs testing

#961 852 - Improve H5P 360 integration to allow opening to a specific scene
  classes/class.tapestry-h5p.php
  classes/class.tapestry-node.php
  templates/vue/src/components/Lightbox/media/H5PMedia/H5PIframe.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/H5pForm.vue
  templates/vue/src/services/H5PApi.js
Labels: ready to merge

#948 932 - TYDE CoS #3 - Create connections popup
  classes/activities/class.circle-of-support.php
  endpoints.php
  endpoints/endpoints.circle-of-support.php
  tapestry.php
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/TapestryApp.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleOfSupport.spec.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/Connections.spec.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/README.md
  templates/vue/src/components/tyde/activities/CircleOfSupport/index.vue
  templates/vue/src/services/TapestryAPI.js
Labels: ready to merge
