Repository tapestry-tool/tapestry-wp, pull requests merged in 2021-03, with the labels that each got.

#959 958 - Add Setting Toggles to Allow Draft Nodes and Submitting Nodes
  classes/class.tapestry.php
  templates/vue/cypress/integration/node-permissions.spec.js
  templates/vue/src/components/Sidebar/NodeReview/index.vue
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/Toolbar/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/components/modals/SettingsModal/index.vue
  templates/vue/src/utils/test.js
Labels: ready to merge

#923 915 - Bug Fix: Admin able to accept child nodes of submitted node
  classes/class.tapestry.php
  endpoints.php
  templates/vue/cypress/fixtures/review.json
  templates/vue/cypress/integration/review.spec.js
  templates/vue/src/components/Sidebar/NodeReview/ReviewButtons.vue
  templates/vue/src/components/Sidebar/NodeReview/index.vue
  utilities/class.tapestry-errors.php
  utilities/class.tapestry-helpers.php
Labels: ready to merge

#954 945 - Bug Fix: Delete draft child nodes from other users upon node deletion
  classes/class.tapestry.php
  endpoints.php
  templates/vue/cypress/fixtures/two-nodes-diff-user.json
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/src/components/modals/NodeModal/DeleteNodeButton.vue
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/store/actions.js
Labels: ready to merge

#976 975 - Fix WP installation for CI
  docker-compose.yml
Labels: ready for review

#929 898- Ask user to refresh page or login if session timed out
  tapestry.php
  templates/libs/es2015-test.js
  templates/vue/.eslintrc.js
  templates/vue/src/App.vue
Labels: almost done, ready for review

#981 #980 Bug fix: Tapestry loading issues
  classes/class.tapestry.php
  templates/vue/src/store/getters.js
Labels: needs testing

#968 966 - Bug Fix: Unable to export tapestry
  endpoints.php
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/src/components/modals/SettingsModal/index.vue
  templates/vue/src/services/TapestryAPI.js
Labels: needs testing

#960 952 - TYDE CoS #5 - Add smart positioning and responsiveness for communities
  classes/activities/class.circle-of-support.php
  endpoints.php
  endpoints/endpoints.circle-of-support.php
  templates/vue/src/components/tyde/activities/CircleOfSupport/CircleOfSupport.spec.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddCommunityForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddCommunityTab.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CommunitiesList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/ConnectionsList.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/ConnectionsTab.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosModal.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosPopup.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/CosPopupButton.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CommunityView/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/AddConnectionForm.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/Connections.spec.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/Connections/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/Connections.spec.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/ConnectionsTab/index.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/CosPopupButton.vue
  templates/vue/src/components/tyde/activities/CircleOfSupport/cos.config.js
  templates/vue/src/components/tyde/activities/CircleOfSupport/index.vue
  templates/vue/src/services/TapestryAPI.js
  templates/vue/src/utils/Helpers.js
Labels: ready for review

#962 953 - Change accordion to multi-content node
  classes/class.tapestry-node.php
  plugin-updates.php
  settings.php
  tapestry.php
  templates/vue/cypress/integration/lightbox/accordion.spec.js
  templates/vue/cypress/integration/lightbox/multicontent.spec.js
  templates/vue/cypress/integration/link-authoring.spec.js
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/modals/NodeModal/DeleteNodeButton.vue
  templates/vue/src/components/modals/NodeModal/forms/BehaviourForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/MultiContentForm/SubItemTable.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/MultiContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
  templates/vue/src/utils/dataset.js
Labels: ready to merge
