Repository tapestry-tool/tapestry-wp, pull requests merged in 2022-06, with the labels that each got.

#1159 Fix link preview instructions to match main README
  .github/mention-to-slack.yml
  README.md
  templates/vue/README.md
  templates/vue/cypress-sample.json
Labels: ready to merge

#1165 1164 - Upgrade node packages and prepare for node v16
  .github/workflows/ci.yml
  templates/vue/.eslintrc.js
  templates/vue/babel.config.json
  templates/vue/config/webpack.base.js
  templates/vue/config/webpack.dev.js
  templates/vue/jest.config.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/MultipleChoiceQuestion/index.vue
  templates/vue/src/main.js
Labels: needs final review, dependencies

#1185 1184 - Bug fix: Test failures on node v16.15.1
  templates/vue/package-lock.json
  templates/vue/package.json
Labels: needs final review, dependencies

#1167 1166 - Adhere to vue/no-mutating-props
  templates/vue/.eslintrc.js
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/index.vue
  templates/vue/src/components/Lightbox/media/VideoMedia/index.vue
  templates/vue/src/components/modals/NodeModal/forms/AppearanceForm.vue
  templates/vue/src/components/modals/NodeModal/forms/BehaviourForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ConditionsForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/Bucket.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/Item.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/DragDropForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/MultipleChoiceForm/ChoiceRow.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/MultipleChoiceForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/AnswerForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/H5pForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/MultiContentForm/SubItemTable.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/MultiContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/PopupForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/TextForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/UrlEmbedForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/VideoForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/WpPostForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/CoordinatesForm.vue
  templates/vue/src/components/modals/NodeModal/forms/CopyrightForm.vue
  templates/vue/src/components/modals/NodeModal/forms/ReferencesForm.vue
  templates/vue/src/components/modals/NodeModal/index.vue
  templates/vue/src/components/modals/common/FileUpload.vue
  templates/vue/src/store/index.js
  templates/vue/src/store/mutations.js
  templates/vue/src/utils/Helpers.js
Labels: ready to merge

#1193 1192 - Replace deprecated Cypress commands
  templates/vue/cypress/integration/import-export.spec.js
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/cypress/integration/lightbox/answer.spec.js
  templates/vue/cypress/integration/lightbox/embed.spec.js
  templates/vue/cypress/integration/lightbox/multicontent.spec.js
  templates/vue/cypress/integration/lightbox/wordpress.spec.js
  templates/vue/cypress/integration/node-appearance.spec.js
  templates/vue/cypress/integration/node-authoring.spec.js
  templates/vue/cypress/integration/node-locked.spec.js
  templates/vue/cypress/integration/settings.spec.js
  templates/vue/cypress/support/commands.js
Labels: ready to merge

#1180 1179 - Bug fix: Importing an exported Tapestry fails
  templates/vue/src/components/TapestryMain/RootNodeButton/index.vue
Labels: ready to merge

#1201 1200 - Bug fix: Empty H5P dropdown
  templates/vue/src/services/H5PApi.js
Labels: needs final review

#1172 1171 - Bug fix: Add video pop-ups in NodeModal
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/MultiContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/common/SubItemTable.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review

#1177 1176 - Bug fix: Creating cycles with Multicontent causes Tapestry to freeze
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review

#1178 1175 - Bug fix: Changing video node to other type retains the media duration
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review

#1183 1182 - Bug fix: Video url not found error for YouTube videos
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/VideoForm.vue
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review

#1188 1187 - Bug fix: Node thumbnails added via link preview disappear on refresh
  classes/class.tapestry-node.php
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review
