Repository tapestry-tool/tapestry-wp, pull requests merged in 2022-09, with the labels that each got.

#1252 1251 - Bug fix: H5P lightbox height is not adjusted after first height change
  templates/vue/src/components/Lightbox/index.vue
Labels: needs final review

#1117 1114 - List activities in a tapestry and allow viewing all user answers
  classes/class.tapestry-node.php
  classes/class.tapestry-user-progress.php
  endpoints.php
  interfaces/interface.tapestry-user-progress.php
  templates/vue/cypress/integration/lightbox/activity.spec.js
  templates/vue/cypress/support/commands.js
  templates/vue/package-lock.json
  templates/vue/package.json
  templates/vue/src/components/Toolbar/UserAnswersButton.vue
  templates/vue/src/components/Toolbar/index.vue
  templates/vue/src/components/modals/UserAnswersModal/index.vue
  templates/vue/src/config/routes.js
  templates/vue/src/services/TapestryAPI.js
Labels: needs final review, dependencies

#1147 1146 - Show completion screen only when all question are done
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/AudioQuestion.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/DragDropQuestion/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/MultipleChoiceQuestion/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/TextQuestion.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/Question/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/index.vue
  templates/vue/src/components/modals/NodeModal/index.vue
Labels: needs final review

#1195 1194 - Option to hide locked nodes
  classes/class.tapestry-node.php
  templates/vue/cypress/integration/node-locked.spec.js
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/MultiContentRow.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/MultiContentRows.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu.spec.js
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/PageMenuItem.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/index.vue
  templates/vue/src/components/TapestryMain/TapestryLink.vue
  templates/vue/src/components/TapestryMain/TapestryNode/index.vue
  templates/vue/src/components/modals/NodeModal/forms/ConditionsForm.vue
  templates/vue/src/fixtures/deep-page.json
  templates/vue/src/store/getters.js
  templates/vue/src/utils/Helpers.js
Labels: needs final review

#1203 1202 - PageMenu redesign
  templates/vue/src/components/Lightbox/TapestryModal/index.vue
  templates/vue/src/components/Lightbox/index.vue
  templates/vue/src/components/Lightbox/media/ActivityMedia/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/PageMenu/index.vue
  templates/vue/src/components/Lightbox/media/MultiContentMedia/index.vue
Labels: needs final review

#1257 1256 - Update package-lock.json to version 2
  templates/vue/package-lock.json
Labels: needs testing
